/**
 * Conseil de Cycle
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserDto } from '../model/models';
import { UpdateUserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createUserDto 
     */
    userAdminControllerCreate(createUserDto: CreateUserDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    userAdminControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    userAdminControllerFindOne(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    userAdminControllerRemove(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param updateUserDto 
     */
    userAdminControllerUpdate(id: number, updateUserDto: UpdateUserDto, extraHttpRequestParams?: any): Observable<{}>;

}
