/**
 * Conseil de Cycle
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateMeetingDto } from '../model/models';
import { MeetingDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MeetingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createMeetingDto 
     */
    meetingControllerCreate(createMeetingDto: CreateMeetingDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    meetingControllerFindOne(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    meetingControllerRemove(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param body 
     */
    meetingControllerUpdate(id: number, body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    meetingsControllerFindAll(extraHttpRequestParams?: any): Observable<Array<MeetingDto>>;

    /**
     * 
     * 
     * @param from 
     * @param to 
     */
    meetingsControllerFindBetween(from: string, to: string, extraHttpRequestParams?: any): Observable<Array<MeetingDto>>;

}
