/**
 * Conseil de Cycle
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserDto } from '../model/models';
import { UpdateUserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createUserDto 
     */
    userControllerCreate(createUserDto: CreateUserDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    userControllerFind(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    userControllerRemove(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param updateUserDto 
     */
    userControllerUpdate(updateUserDto: UpdateUserDto, extraHttpRequestParams?: any): Observable<{}>;

}
