/**
 * Conseil de Cycle
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserDto { 
    email: string;
    password: string;
    firstName: string;
    name: string;
    role: CreateUserDto.RoleEnum;
}
export namespace CreateUserDto {
    export type RoleEnum = 'user' | 'admin';
    export const RoleEnum = {
        User: 'user' as RoleEnum,
        Admin: 'admin' as RoleEnum
    };
}


