/**
 * Conseil de Cycle
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './user-dto';


export interface MeetingDto { 
    id?: number;
    date?: string;
    location?: string;
    createdBy?: UserDto;
    updatedBy?: UserDto;
}

